{{- if .Values.calcom.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calcom.secretName" . }}
  labels:
    {{- include "calcom.labels" . | nindent 4 }}
type: Opaque
data:
  nextauth-secret: {{ .Values.calcom.secrets.nextAuthSecret | default (randAlphaNum 32) | b64enc }}
  encryption-key: {{ .Values.calcom.secrets.encryptionKey | default (randAlphaNum 32) | b64enc }}
  {{- if .Values.postgresql.enabled }}
  database-password: {{ .Values.postgresql.auth.password | b64enc }}
  {{- else if .Values.calcom.database.external }}
  database-password: {{ required "Database password is required for external database" .Values.calcom.database.password | b64enc }}
  {{- end }}
  {{- if .Values.calcom.secrets.email.serverPassword }}
  email-password: {{ .Values.calcom.secrets.email.serverPassword | b64enc }}
  {{- end }}
  {{- if .Values.calcom.secrets.google.apiCredentials }}
  google-api-credentials: {{ .Values.calcom.secrets.google.apiCredentials | b64enc }}
  {{- end }}
  {{- if .Values.calcom.secrets.microsoft.graphClientId }}
  ms-graph-client-id: {{ .Values.calcom.secrets.microsoft.graphClientId | b64enc }}
  ms-graph-client-secret: {{ .Values.calcom.secrets.microsoft.graphClientSecret | b64enc }}
  {{- end }}
  {{- if .Values.calcom.secrets.zoom.clientId }}
  zoom-client-id: {{ .Values.calcom.secrets.zoom.clientId | b64enc }}
  zoom-client-secret: {{ .Values.calcom.secrets.zoom.clientSecret | b64enc }}
  {{- end }}
{{- end }}
